---

name: add issue to projects

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-community:
    steps:
      - name: Add issue to Community project
        uses: Senzing/build-resources/.github/workflows/add-to-project.yaml@main
        with:
          project-number: "2"
          classic: true

  add-issue-to-devsecops:
    steps:
      - name: Add issue to DevSecOps project
        uses: Senzing/build-resources/.github/workflows/add-to-project.yaml@main
        with:
          project-number: "13"
          classic: false
