---

name: add issue to projects

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-community:
    uses: Senzing/build-resources/.github/workflows/add-to-project.yaml@main
    with:
      project-number: "2"
      classic: true

  add-issue-to-devsecops:
    uses: Senzing/build-resources/.github/workflows/add-to-project.yaml@main
    with:
      project-number: "13"
      classic: false
