---

name: 'dependabot approve and merge'

on: 
  workflow_call:
    secrets:
      TEMP_SKERN_PR_RW_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-approve-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'kernelsam' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve patch version PRs
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.TEMP_SKERN_PR_RW_TOKEN }}
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
          review-message: "Automated: **approving** this pull request because **it includes a patch update**"
        # if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        #run: |
        #  gh pr review --approve "$PR_URL" -b "I'm **approving** this pull request because **it includes a patch update**"
        #env:
        #  PR_URL: ${{ github.event.pull_request.html_url }}
        #  GH_TOKEN: ${{ secrets.TEMP_SKERN_PR_RW_TOKEN }}
        #  GH_DEBUG: '1'
      - name: Auto merge patch version PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
